[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin-allow-popups"
    Cross-Origin-Embedder-Policy = "credentialless"
    Content-Security-Policy = "frame-ancestors 'self' https://discord.com https://*.discord.com"
    Access-Control-Allow-Origin = "*"
